apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-sample-app
  template:
    metadata:
      labels:
        app: react-sample-app
    spec:
      containers:
        - name: react-sample-app
          image: ghcr.io/<YOUR_GITHUB_USERNAME>/react-sample-app:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret      
---
apiVersion: v1
kind: Service
metadata:
  name: react-sample-app-service
  namespace: default
spec:
  selector:
    app: react-sample-app
  ports:
    - protocol: TCP
      port: 80        # The port that other pods in the cluster will use to access this service
      targetPort: 8080 # The port on the pod that the service should forward traffic to
  type: ClusterIP
