apiVersion: v1
kind: Service
metadata:
  name: react-sample-app-service
  namespace: default
spec:
  selector:
    app: react-sample-app
  ports:
    - protocol: TCP
      port: 80        # The port that other pods in the cluster will use to access this service
      targetPort: 8080 # The port on the pod that the service should forward traffic to
  type: ClusterIP
